stages:
  - release

attach_script_to_tag:
  stage: release
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apk add --no-cache curl jq
  script:
    - echo "📦 Uploading create_project.exs for tag $CI_COMMIT_TAG"
    - curl --request POST --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --form "file=@priv/scripts/create_project.exs" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/uploads" | tee upload.json
    - FILE_URL=$(jq -r .url upload.json)
    - echo "✅ Script uploaded successfully!"
    - echo "🔗 Download URL: ${CI_PROJECT_URL}${FILE_URL}"
    - echo "🏷️ Associated with tag: $CI_COMMIT_TAG"