release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE<br><br>To Download:<br><code>curl -o create_project.exs $CI_PROJECT_URL/-/raw/$CI_COMMIT_SHA/priv/scripts/create_project.exs?inline=false</code>"
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_SHA"
    assets:
      links:
        - name: "main_script"
          filepath: "/priv/scripts/create_project.exs"
          url: "$CI_PROJECT_URL/-/raw/$CI_COMMIT_SHA/priv/scripts/create_project.exs?inline=false"
          link_type: "other"