stages:
  - release

release_project_script:
  stage: release
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG   # only run on tags
  script:
    - echo "Attaching priv/scripts/create_project.exs to release $CI_COMMIT_TAG"
    - apk add curl
    - apk add wget
    # Create a release if it doesn't exist, or update if it does
    - |
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
        --upload-file priv/scripts/create_project.exs \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/uploads" \
        | tee upload.json
    - FILE_URL=$(jq -r .url upload.json)
    - |
      curl --request POST \
        --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
        --header "Content-Type: application/json" \
        --data "{
          \"name\": \"Release $CI_COMMIT_TAG\",
          \"tag_name\": \"$CI_COMMIT_TAG\",
          \"assets\": {
            \"links\": [
              {
                \"name\": \"create_project.exs\",
                \"url\": \"${CI_PROJECT_URL}${FILE_URL}\"
              }
            ]
          }
        }" \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"