name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get tag message
        id: tag-message
        run: |
          TAG_MESSAGE=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
          echo "message=$TAG_MESSAGE" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          body: ${{ steps.tag-message.outputs.message }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            priv/scripts/create_project.exs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}